### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by Alcha** [EvotecIT/PSWriteWord#1]
I just stumbled upon this project due to [your post][0] on the PowerShell Scripting group on Facebook. You mentioned in [your overview][1] that:

"_Some of those commands are not yet finished and some are going to evolve. Some will get new features, some will be deprecated (or not really needed)._"

What exactly needs to be worked on? Is there any way in which I can help?

[0]: https://www.facebook.com/evotecpl/posts/1715894811796918
[1]: https://evotec.xyz/hub/scripts/pswriteword-powershell-module/

**Comment by PrzemyslawKlys** [comment]
Well.. I am working on Headers/Footers now. But there are bookmarks that are not added. Hyperlinks/Equations and few other things have basic functionality. And since they apply to paragraph essentially Add-WriteText kind of applies to them as well. So i need to extract add-writetext settings to another support function which then will be used in 3 or more cases to apply colors etc for hyperlinks/equations. There are probably other features in DocX library that I have not touched yet. Then there is add-wordtable, add-wordlist that was tested in very few cases. I assume it will blow up on harder objects or different use cases. I would also like some functions to work via pipeline so you can actually do $object | Add-WordTable -WordDocument $WordDocument and it would work. Also I need to make sure that processing is done properly. I do no try/catch, just basic error checking. Make your pick ;-) probably if people start to use it (or myself) there will be things that needs changing because it doesn't make sense.

**Comment by PrzemyslawKlys** [comment]
Then there is also pagelayout (orientation) that needs to be done.

**Comment by PrzemyslawKlys** [comment]
And then basically all read methods (loading word, changing things, copying things) etc.

**Comment by Alcha** [comment]
Perfect! In that case when I have some free time this weekend I'll see what I can do to help.

**Comment by PrzemyslawKlys** [comment]
I've added today lots of stuff and changed things around. Make sure that if you start on something on saturday to review what's there :-)
