### ISSUE TITLE
Find String/Bookmark and create a Table at this position.

### ISSUE THREAD

**Issue by LoniBoy** [EvotecIT/PSWriteWord#25]
Hi,
thank you so much for this great module!!

But i have a little Problem as you can see in the title.
I just have the parameter "position" at the "Add-WordTable"-Section.
But i cant figure out the position/line for my Bookmark.
With your functions i just can see the type and the name. Also the .xml-file doesn't show any informations for line...
At the moment i must define a static INT for setting the table on a specific position.
Maybe do you have an idea.

Best regards,
Leon

**Comment by PrzemyslawKlys** [comment]
Hi, you can probably loop thru paragraphs and find the text in a paragraph. When having paragraph it should be easy to clear that paragraph and add a table to it.

**Comment by LoniBoy** [comment]
Perfect! It works..
Thanks

**Comment by LoniBoy** [comment]
Ok my mistake... no i have another Problem.
I want to add the table at Position/Paragraph XY.
But the Parameter( -Position) doesnt work.
I thought i already tested it with success. 

Each time the table is appended at the End.
How can i solve this?
Thanks.

**Comment by LoniBoy** [comment]
Got it.

Add-WordTable -WordDocument $WordDocument -DataTable $myitems2 -Paragraph $WordDocument.Paragraphs[XY]

**Comment by PrzemyslawKlys** [comment]
Glad you solved this!

**Comment by matmaer** [comment]
> 
> Got it.
> 
> Add-WordTable -WordDocument $WordDocument -DataTable $myitems2 -Paragraph $WordDocument.Paragraphs[XY]

Could you elaborate a bit more on how you got this working?  If I try this it works to insert a table in certain paragraphs, like table cells but not paragraphs that only contain text....

Add-WordTable : Cannot process argument transformation on parameter 'Paragraph'. Cannot convert the "System.Collections.ObjectModel.Collection`1[Syste
m.Management.Automation.PSObject]" value of type "System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSObject, System.Managemen
t.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]" to type "Xceed.Document.NET.InsertBeforeOrAfter".
At line:1 char:73

I know this issue is few months old but I'd love to make this work...

**Comment by LonBoy98** [comment]
> > Got it.
> > Add-WordTable -WordDocument $WordDocument -DataTable $myitems2 -Paragraph $WordDocument.Paragraphs[XY]
> 
> Could you elaborate a bit more on how you got this working? If I try this it works to insert a table in certain paragraphs, like table cells but not paragraphs that only contain text....
> 
> Add-WordTable : Cannot process argument transformation on parameter 'Paragraph'. Cannot convert the "System.Collections.ObjectModel.Collection`1[Syste m.Management.Automation.PSObject]" value of type "System.Collections.ObjectModel.Collection`1[[System.Management.Automation.PSObject, System.Managemen
> t.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]" to type "Xceed.Document.NET.InsertBeforeOrAfter".
> At line:1 char:73
> 
> I know this issue is few months old but I'd love to make this work...

what exactly do you mean?
in my case i have template with keywords like "<~keyword~>"
I then loop through every line and search for this specific keyword.
When i found the line(number), i can add the table at this specific paragraph with the code above.
Maybe you must delete the keyword afterwards(take the paragraph-line - 1).

Maybe you can post some code.

**Comment by matmaer** [comment]
> what exactly do you mean?
> in my case i have template with keywords like "<~keyword~>"
> I then loop through every line and search for this specific keyword.
> When i found the line(number), i can add the table at this specific paragraph with the code above.
> Maybe you must delete the keyword afterwards(take the paragraph-line - 1).
> 
> Maybe you can post some code.

Thanks I got it to work.  The issue was that I retrieved the paragraph like this:
$target_paragraph = $WordDocument.Paragraphs.Where({$_.Text -eq "<keywordtext>"})
Add-WordTable -WordDocument $WordDocument -DataTable $mytable -Paragraph $target_paragraph

However if I specify the paragraph (or line) number like you suggested, it works. For example:
Add-WordTable -WordDocument $WordDocument -DataTable $mytable -Paragraph  $WordDocument.Paragraphs[407]

$target_paragraph and $WordDocument.Paragraphs[407] look the same in the terminal, but they have a different Type.

Thanks a lot for your reply!
