### ISSUE TITLE
(Request) - Ability to specify Font Size for Add-WordTable content

### ISSUE THREAD

**Issue by PenguinPaws** [EvotecIT/PSWriteWord#4]
When adding a table, I would like to be able to specify the Font-Size for all the content in the table, similar to how I can use the " -FontSize " parameter when adding Paragraphs.

(I don't seem to be able to tag this with the "request" label, so I put it in the title)

**Comment by guidooliveira** [comment]
I'll try to work on that

**Comment by PrzemyslawKlys** [comment]
Hello, Since I had other plans regarding Set-WordText... I actually added basic color, bold, italic, fontsize, fontfamily to sources and published as module 0.4.2. Sorry @guidooliveira ;-) 

Added Example-Tables9.ps1 showing this. Basically the trick is first array entry is for header, next one is for 1st row, 2nd row and so on. 

```
Add-WordTable -WordDocument $WordDocument -DataTable $InvoiceData -AutoFit Window -Color Blue, Green, Red -FontSize 15, 10, 8 -Bold $true, $false, $false -FontFamily 'Arial', 'Tahoma'
```

This is of course basic. May need to plan on how to process it for whole table.. right now if it's not set it doesn't do anything. Maybe there should be a switch triggering 1st entry in array to be header, 2nd entry in array to be for the rest of the table. 

Generally Add-WordTable should and will support all options that Add-WordText has. Just need some supportive functions so it's not a mess to maintain. 

@PenguinPaws  can you let me know what you think? 
@guidooliveira  hope this design is fine with you?

**Comment by PrzemyslawKlys** [comment]
It has to be flexible, at same time it's actually easier to add then working with static entries. I was thinking that by adding: -ContinueFormatting switch it would take the last formatting and apply it to everything in the table. So if you provide 1 entry it would apply it to all table data (including headers). If you add 2 entries then it would apply 1st to headers, 2nd to table 1st row and continue other rows. If you don't set the formatting then it will do what it is doing now. I am also thinking on adding supportive commands like Set-WordTable -Table ... -All or something where you could use it at the end of your script and it would format all tables according to specific requirements. Just like it does now for the -language part on Save-WordDocument.

**Comment by PenguinPaws** [comment]
I like the idea of having the "-ContinueFormatting" switch. This way we still get the flexibility of setting formatting per row.

Would the " -Table " in Set-WordTable take in a list of tables that will have the same formatting (and therefore we can use this command multiple times for groups of table formats), or will it be a single formatting that is applied globally in the file?

**Comment by PrzemyslawKlys** [comment]
Good idea. Will try to implement that when I'm done with new PSWinReporting features.

**Comment by PrzemyslawKlys** [comment]
It's released. Added a lot of other options too thou
